language: node_js
node_js:
- '5.6'
notifications:
  hipchat:
    rooms:
      secure: OK7MU1O8ccG5Ns2ByoOwK70luq262Yje6bdHWLlOHuUGMoKnxDY1iYTl6EVW7+Sdw+5ldyI8Z30QvwV5t38kZBvlkTVnOd3W9S9MXdjF32ZQpTlEzXYnL450foEdrqTyQG9XO6r9SCMQRryz7+gjO1TdJv1JdwmbBVOeYknrl1g=
